group: bluezone
sudo: required
before_install:
  - export TZ=Etc/UTC
language: node_js
node_js: "8"
notifications:
  slack: ibm-aic-offerings:pKEkgH3hXaZQg8UCl6eLWyYB
cache:
  npm: true
  directories:
    - node_modules
script:
  - npm install && npm run test
